let element1 = document.getElementsByTagName("div");
let element2 = document.getElementById("elzero");
let element3 = document.getElementsByClassName("element");
let element4 = document.getElementsByName("js");
let element5 = document.body.children[1];
let element6 = document.all.elzero;
let element7 = document.querySelector("div");
let element8 = document.querySelector("#elzero");
let element9 = document.querySelector(".element");
let element10 = document.querySelector("[name=js]");
let element11 = document.querySelectorAll("div");
let element12 = document.querySelectorAll("#elzero");
let element13 = document.querySelectorAll(".element");
let element14 = document.querySelectorAll("[name=js]");
let element15 = document.body.children.namedItem("elzero");
let element16 = window.elzero;

console.log(element1[0]);
console.log(element2);
console.log(element3[0]);
console.log(element4[0]);
console.log(element5);
console.log(element6);
console.log(element7);
console.log(element8);
console.log(element9);
console.log(element10);
console.log(element11[0]);
console.log(element12[0]);
console.log(element13[0]);
console.log(element14[0]);
console.log(element15);
console.log(element16);
